---
title: "R Notebook"
output: html_notebook
---
Homework: Analyze, Can you see any patterns?, Knit, Create a document
```{r}
library(readr)
library(lubridate)
library(ggplot2)
library(dplyr)
```

###Data

```{r}
Fraud_Data <- read_csv("Fraud/Fraud_Data.csv")
IpAddress_to_Country <- read_csv("Fraud/IpAddress_to_Country.csv")
```

```{r}
head(Fraud_Data, n=10)
```
```{r}
head(IpAddress_to_Country, n=10)
```

###General Data Exploration

```{r}
names(Fraud_Data)
```
```{r}
nrow(Fraud_Data)
```

```{r}
ggplot(Fraud_Data, aes(class)) + geom_histogram()
```
```{r}
group_by(Fraud_Data, class) %>%
  count()
```
###Brower
Which browser has the most frauds?
```{r}
brow <- group_by(Fraud_Data, browser, class) %>%
  count(brow)
brow
```
```{r}
ggplot(data = brow)+
  geom_bar(stat = "identity",
    mapping = aes(x=browser,y=n, fill = as.factor(class)),
          position = "dodge")
```

Chrome has more fraud than IE than Safari than FireFox than Opera
Is the proportion similar of fraud vs not fraud?

```{r}
dseconds(Fraud_Data$purchase_time[1])
```
```{r}
head(Fraud_Data)
```
```{r}
by_cyl <- mtcars %>% group_by(cyl)

# grouping doesn't change how the data looks (apart from listing
# how it's grouped):
mtcars
```

```{r}
purchase_time_vs_class <- group_by(Fraud_Data, purchase_time, class) %>%
  count() %>%
  ungroup() %>%
  mutate(class=as.factor(class))
purchase_time_vs_class
ggplot(purchase_time_vs_class) +
  geom_bar(stat = "identity", aes(x = purchase_time, y = n, fill = class), position = "dodge")
```


```{r}
  count(brow)
```









